L1.Execution of Book Queries on the pre-created Employee DB .
a. Queries using %LIKE%, BETWEEN,
b. Queries using Functions, GroupBy, Having, OrderBy
c. At least one Correlated and Nested Query

=====================================

CREATE TABLE L1_EMPLOYEE(
FNAME VARCHAR(20),
MINIT VARCHAR(20),
LNAME VARCHAR(20),
SSN INT PRIMARY KEY,
BDATE DATE,
ADDRESS VARCHAR(25),
SEX CHAR(1),
SALARY INT, 
SUPER_SSN INT,
DNO INT,
FOREIGN KEY(DNO) REFERENCES L1_DEPARTMENT(DNO),
FOREIGN KEY(SUPER_SSN) REFERENCES L1_EMPLOYEE(SSN));

CREATE TABLE L1_DEPARTMENT(
DNAME VARCHAR(20),
DNUMBER INT PRIMARY KEY,
MGR_SSN INT,
MGR_START_DATE DATE,
FOREIGN KEY(MGR_SSN)REFERENCES L1_EMPLOYEE(SSN));

CREATE TABLE L1_DEPT_LOCATIONS(
DNUMBER INT,
DLOCATION VARCHAR(20),
PRIMARY KEY(DNUMBER,DLOCATION),
FOREIGN KEY L1_DEPT_LOCATIONS(DNUMBER) REFERENCES L1_DEPARTMENT(DNUMBER));

CREATE TABLE L1_PROJECT(
PNAME VARCHAR(20),
PNUMBER INT PRIMARY KEY,
PLOCATION VARCHAR(20),
DNUM INT,
FOREIGN KEY(DNUM) REFERENCES L1_DEPARTMENT(DNUMBER));

CREATE TABLE L1_WORKS_ON(
ESSN INT,
PNO INT,
HOURS INT,
PRIMARY KEY(ESSN,PNO),
FOREIGN KEY(PNO) REFERENCES L1_PROJECT(PNUMBER),
FOREIGN KEY(ESSN) REFERENCES L1_EMPLOYEE(SSN));

CREATE TABLE L1_DEPENDENT(
ESSN INT,
DEPENDENT_NAME VARCHAR(20),
SEX CHAR(1),
BDATE DATE,
RELATIONSHIP VARCHAR(10),
PRIMARY KEY(ESSN,DEPENDENT_NAME),
FOREIGN KEY L1_DEPENDENT(ESSN) REFERENCES L1_EMPLOYEE(SSN));